
[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"
