version: 2
repo:
  public: go-server-sdk-evaluation
  private: go-server-sdk-evaluation-private

jobs:
  - docker:
      image: golang:1.18-buster
    template:
      name: go

branches:
  - name: v3
  - name: v2
  - name: v1

publications:
  - url: https://pkg.go.dev/github.com/launchdarkly/go-server-sdk-evaluation/v2
    description: documentation
