version: 2
repo:
  public: go-server-sdk-evaluation
  private: go-server-sdk-evaluation-private

jobs:
  - docker:
      image: golang:1.14-buster
    template:
      name: go
    env:
      LD_RELEASE_GO_IMPORT_PATH: gopkg.in/launchdarkly/go-server-sdk-evaluation.v1

branches:
  - name: v2
  - name: v1

publications:
  - url: https://pkg.go.dev/gopkg.in/launchdarkly/go-server-sdk-evaluation.v1
    description: documentation
